version: "3.8"

services:
  mongodb:
    image: mongo

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DEPLOYED=docker
    depends_on:
      - mongodb

  angular:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 8080:80

    depends_on:
      - nodejs
